language: node_js
node_js:
- 10.15.3
cache: npm
script:
- npm run test:prod
deploy:
  provider: heroku
  app: jist-screenshotter
  api_key:
    secure: hjmwwJOndrnmMAR6gdtD8LjeSnvmPK8xeFOqNjDL3R5gjXxR22Vxsf01sI/mvJVb4bizt311nOkYsIdiNk9jX6ZppiEqb6TD0GEWElhXSeduMu8fj3eSLOjuy7KYocSalPxXp+aDDpTII1BYFgB9kVgVvo267e1ebwTeGQyCjXEw47W1xZKHJCn39RcvxRNeAz4JYZNcj1kHjDp5ySjq6/I9eiei7RRVcL48p3MRRnZ6JJWHtH3FXWzf3rzQ/gxZXUy1pBPxtJ9WSEUh39oleRuakj1tTBnkvgDMB/TU19OWymMzCl1dXDjb/1X3QbdBBZLhZNl5lTDBkpmni8pfkDjvRULa4/Acu/lVwYB2vNORMJcec7vTVKdXHhL0GJgipKdeHpyrnC1Qifpk2ytcT4czZpRMHmVaHxJQzGxY7EzouWEsrrT48pMop9T7U6dan/9+Lj4c7bBTj208jqs2VTkLMLsVMlN8uhbkPQRKeo0ElpCY3PPviL0qsN1W1CE1l5wYYqKuuBF61VmAQ529+kV7U3Ag5hVhRD0KKknVSoIYxfueGDkS9NQRa8AbQ1Ceyw4ahSuP3WaMC3gbsbSbtpEzGcXtusm1GzZL5sUEI6NryHFwU81YwmUhjmzzsxG0kGGyYR4w0VhlDjhVSytWD/Bt6/YCYBzUoX1s+k8RfoM=
