language: node_js
node_js:
  - 10.15.3
cache: npm
script:
  - npm run test:prod
deploy:
  provider: heroku
  app: jist-screenshotter
  api_key:
    secure: i0HIjcY17fUvFlqgCY/l3pkIUcGNtyutzCfcx2lkVs0gFPiYK1LFikqmVV2NKrOw5xLnREwVE9KLtee/AnvjgdrN1BjjksBLxRJyeRCcvlq7la0OJ3U0To+dfeVp3kLaMKXsODxjyFS5Mk9Jb3f+15x5fir+tlp6E/LIIC4PjFAH4nQnA6eyKRR/DDMumHCC4Q/jjhLsW8s4woTUR6KuyZsJFZ9WYSgsLtkC6ydtu2gFiafVp5RL3POp9YnOT0hykG3UBD3p00xUxW5xZQDxsxWXyTdjZ8UO23QpZwjwMgF7S792tQ34zOr33WCOv6xOXPo4cNh+MIiJNiA/5CrFoWdJDC2Mko4nNEpQILPyUED+A6xMlLssXrrUBbPAfVJDfLh/KE8agQ0f0iu+/krxv4kVQJyWKWTTCeKx2ocPwT98HuA0CcbJUcxOftd7x4b3gKw/wHj24WoctZ8Bw1gX95BNbXyfQBe2jn0RMutAu6qPJm2THfLcLVzJcyVq9nFzi70pZ1UfgGeE+s7sKdey6rs50iuwMfWfA/cAPoxaDbVKeRFNS1fiOiwkBKHIDt+VKqRbH6f9vCds3yjbRIzd/mZIlIYCrbCon6upYTN/JHizr84SQkv8rfBUvCsbUBV1GcdSCk/GjYfvDJeRGk9gNHVzNGggcpyjesGvuUE/up4=
