language: node_js
node_js:
- 10.15.3
cache: npm
script:
- npm run test:prod
deploy:
  provider: heroku
  app: jist-screenshotter
  api_key:
    secure: FK2cSmxU4oe5pPF+Wg3oOXZzkaJluA3I1T3/Sfobp6jp623UNr2w4UhyiKnmMQzO2aZoFkKSOO8Jam8syBOY/jFqFtGBV6unzsnlz2WXG/djIbKH95xr7kiWzxfABWmr+NaVTCDqSlHeQjXi9hzDI+ymDb58XjHQ/SvEqBGsMJ8JEf8V4FGzX2kP1lJYseTsJPJhhuD1CxggOJBTn34w7JSl6op5m+fGLLdpcV6Ih7tvCASHno8I8ejvy4GQ4RkpCodv1U9JDsGefgQosgsH0TxKYuJtAOZuuMIngTi6Svs1+0R6GfqarDklQ2eJU0pp+ULl6Jb/aY8tu1K65Bb6auY8XD3EZCXhNrwXJjsXEnMOm36wV28xOH6xJtfbyM1BLTfbl+K89MMnW5QlVSgDAHn6G62SH4v+FBjQCupMHVxvhF4BkOcqaF95yddzLr7PWktCkS3JBYms0hcYt9MDI9ij9hSC0r2zDylgiUQIYkoskMFzYSiGseaV1RfUDixU3YLdrh1wEubos2JKLAO36le41WZ8diYC8VdVPTs3rxUUMF1VgOxhV/EPqiUPDQNI69ebaVX2oW/y7WDwiokd1Re+5KXIJZqRZXEVxc1lbtwvCPAO6vcc7iGl+RbtY1UrWwEDjQgCuuu0iMrseEvFeeU5oOQvCNzUm4fefzDdwk4=
