language: node_js
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
cache: npm
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - npm run test:prod
deploy:
  provider: heroku
  app: jist-screenshotter
  api_key:
    secure: F+NPIdfGEgY0LCX+xCvaB9C+fdnioi6v++Q89zhkfQq0jTl5e6+qX+22CcrAifXwbk+XFfB2uXtkikJA06n886eVwnT8vLQ503RGc1fsTZfxIhA085nOMq9uf7kU0gv2aMC8gnmuFF1a3Pe2a3+IHFz0bz40J5F88oTl5XQNi+eL6m2YvIVpTx4tGy1y5zWD3eYUvPjY2DhmS6IBjZvfjzl9kHQlJ43QPok+c1eX7F6tVDwVfwuJuGDiTXFRkcilErfbrL6OPZ6qxxSlBMBZVtNJwm1ig3iDqXS/bmmpTIoutLqCQU8mOrR+svWAq52rWsW7V7uonakgm7wGKXrJOfLJjmAK0vcxViDln1AGt85EAB9swD6sRev0A3NPn2p8fsm5Alye36VO+1Etov/UojgHQyt7RV9fybyPhxh48oR/Eg+G61Gn2i+KH/onYdIg/Z32ZeZ0ZM9Z0G/PzqLIq2J9haTcN8xKQoMe4QEGbF0SeE6vbxCjhEdb+sNGj2cPF/B3Z5s29FmlCNjXkcL1WxFLb7uD7QG6X4lHjgloXytjzUHuUccGJEWbFOsSIlgM96YfhxIm8ZEE4UNpkgqVE4vRPzoKdheWVbkefHGaxUu7G83XMbrqF5lJ0g9cRFjyYz5kXVF2h2n3ddH9+W7bU3447df9KHYOtj35UxdDttY=
